.\" Plog documentation
.TH Plog 2
.UC
.SH NAME
Plog query \- get_plog_size, get_plog_byPID, get_plog_byindex - plog query functions
.SH SYNOPSIS
#include <unistd.h>

int get_plog_size();
int get_plog_byPID(int pid, long * c_time, long * t_time);
int get_plog_byindex(int index, long * c_time, long * t_time);

.SH DESCRIPTION
The functions get_plog_byPID and get_plog_byindex allow the user to query the plog circular buffer using the process' PID value the index to the table ( 0 <= index < get_plog_size()). Both functions will store the information in the variables pointed by c_time (creation time) and t_time (termination time). get_plog_size will return the size of the buffer (which can be changed during compile time).
.SH RETURN VALUES
get_plog_size will return the maximum index that can be accepted by the function get_plog_byindex.
get_plog_byPID will return 0 if lookup is successful or an error value of 2 to indicate PID not found.
get_plog_byindex will return 0 if lookup is successful or an error value of 3 to indicate index out of range.
.SH SEE ALSO        
start_plog (2), stop_plog (2), reset_plog (2)
.SH BUGS            
No known bugs have been reported.
.SH AUTHOR    
Benjamin Babtsov (ben.babtsov@ufl.edu)
